### ISSUE TITLE
Success page

### ISSUE THREAD

**Issue by ngabonzizaguy** [ngabonzizaguy/Hamanhig_Ecom#7]

**Comment by Ha-Quoc-Huy** [comment]
can i do this issue

**Comment by ngabonzizaguy** [comment]
> can i do this issue

That would be great, but can I first know how you'd like to do that?

**Comment by Ha-Quoc-Huy** [comment]
For the Success Page, I'm thinking of a layout with a title like 'Success!' at the top, followed by a success icon, and a short message (e.g., "Your action was completed successfully."). At the bottom, there will be a button to navigate back to the home page or continue with another action. Let me know if this sounds good! thanks

**Comment by ngabonzizaguy** [comment]
> For the Success Page, I'm thinking of a layout with a title like 'Success!' at the top, followed by a success icon, and a short message (e.g., "Your action was completed successfully."). At the bottom, there will be a button to navigate back to the home page or continue with another action. Let me know if this sounds good! thanks

This would be great. would you mind creating a separate branch for that?

**Comment by ngabonzizaguy** [comment]
> > For the Success Page, I'm thinking of a layout with a title like 'Success!' at the top, followed by a success icon, and a short message (e.g., "Your action was completed successfully."). At the bottom, there will be a button to navigate back to the home page or continue with another action. Let me know if this sounds good! thanks
> 
> This would be great. would you mind creating a separate branch for that?

Or, would you rather assist on another issue?

**Comment by Ha-Quoc-Huy** [comment]
Can you asign me to work the success page issue?
